### ISSUE TITLE
python-consul module is missing

### ISSUE THREAD

**Issue by ramshazar** [torque59/garfield#1]
After downloading Garfield and installing the requirements I got an error when I ran the command described under "Sample Usage".

`python -m garfield.core zk --ip 127.0.0.1 --port 31337
   _____             __ _      _     _
  / ____|           / _(_)    | |   | |
 | |  __  __ _ _ __| |_ _  ___| | __| |
 | | |_ |/ _` | '__|  _| |/ _ \ |/ _` |
 | |__| | (_| | |  | | | |  __/ | (_| |
  \_____|\__,_|_|  |_| |_|\___|_|\__,_| v0.01
   -= Distributed System Pwning Cat =-
      -= It's all about ME-OW! =-
    -= @torque59 & @tunnelshade =-
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/tmp/garfield/Garfield-develop/garfield/core.py", line 109, in <module>
    core = Core()
  File "/private/tmp/garfield/Garfield-develop/garfield/core.py", line 26, in __init__
    self._load_plugins()
  File "/private/tmp/garfield/Garfield-develop/garfield/core.py", line 50, in _load_plugins
    plugin = file_utils.get_plugin(*self._plugins[module_props["identifier"]])
  File "garfield/lib/file_utils.py", line 21, in get_plugin
    module = import_module(os.path.dirname(config_path), module_props["module"])
  File "garfield/lib/file_utils.py", line 17, in import_module
    return(imp.load_module(module_name, file, pathname, description))
  File "/private/tmp/garfield/Garfield-develop/garfield/plugins/consuld/consuld.py", line 2, in <module>
    from garfield.plugins.consuld import fingerprinter,attacks
  File "garfield/plugins/consuld/attacks.py", line 3, in <module>
    import consul
ImportError: No module named consul`

After installing python-consul with pip this error was fixed.

Should I create a pull request for this? I assume it is easier to just add the line in the requirements.txt.

**Comment by torque59** [comment]
Thank you @ramshazar , i have updated the requirements file 👍 .
